version: "3.8"
services:
    php-micro-service-deliveries:
        depends_on:
            - mysql-micro-service-deliveries
        build:
            context: .
            dockerfile: Dockerfile
        container_name:  micro-service-deliveries-php
        # restart: always
        tty: true
        volumes:
            - ./:/var/www/html/public
            - ./php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
        networks:
            - micro-services-aleria-network

    nginx-micro-service-deliveries:
        depends_on:
            - php-micro-service-deliveries
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: nginx-micro-service-deliveries
        # restart: always
        tty: true
        ports:
            - "${APP_PORT}:80"
        networks:
            - micro-services-aleria-network

    mysql-micro-service-deliveries:
        image: mariadb
        container_name: db-micro-service-deliveries
        env_file:
            - .env
        environment:
            MARIADB_DATABASE: ${DB_DATABASE}
            MARIADB_USER: ${DB_USERNAME}
            MARIADB_PASSWORD: ${DB_PASSWORD}
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}

        ports:
        - "${DB_PORT}:3306"
        volumes:
        - mysql-micro-service-deliveries:/var/lib/mysql
        - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
        networks:
        - micro-services-aleria-network

volumes:
    mysql-micro-service-deliveries:
networks:
    micro-services-aleria-network:
