version: "3.8"
services:
    app:
        container_name: deliveries-microservice
        build: .
        ports:
            - 8080:80
        volumes:
            - ./:/var/www/html
        networks:
            - alegra-test-network
        depends_on:
            - database
    database:
        image: mysql
        container_name: deliveries-microservice-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        env_file:
            - .env
        ports:
            - 3306:3306
        volumes:
            - deliveries-microservice-db:/var/lib/mysql
        networks:
            - alegra-test-network
    redis:
        image: 'redis'
        container_name: deliveries-microservice-redis
        ports:
            - 6379:6379
        volumes:
            - deliveries-microservice-redis:/data
        networks:
            - alegra-test-network

volumes:
    deliveries-microservice-db:
    deliveries-microservice-redis:

networks:
    alegra-test-network:
