version: "3.8"
services:
    php:
        depends_on:
            - mysql
        build:
            context: .
            dockerfile: Dockerfile
        container_name:  app-deliveries
        # restart: always
        tty: true
        volumes:
            - ./:/var/www/html/
            - ./php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
        networks:
            - deliveries-net

    nginx:
        depends_on:
            - php
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: api-deliveries
        restart: always
        tty: true
        ports:
            - "${APP_PORT}:80"
        networks:
            - deliveries-net

    mysql:
        image: mariadb
        container_name: db-deliveries
        env_file:
            - .env
        environment:
            MARIADB_DATABASE: ${DB_DATABASE}
            MARIADB_USER: ${DB_USERNAME}
            MARIADB_PASSWORD: ${DB_PASSWORD}
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}

        ports:
        - "${DB_PORT}:3306"
        volumes:
        - db-data:/var/lib/mysql
        - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
        networks:
        - deliveries-net

    supervisor:
        build:
            context: ./supervisor
            dockerfile: Dockerfile
        container_name: supervisor-deliveries
        volumes:
        - ./:/var/www/html/
        networks:
        - deliveries-net

    cron:
        build:
            context: ./cron
            dockerfile: Dockerfile
        container_name: cron-deliveries
        volumes:
        - ./:/var/www/html/
        networks:
        - deliveries-net

    redis:
        image: 'redis'
        container_name: redis-deliveries
        ports:
        - 6379:6379
        volumes:
        - dev_redis:/data
        networks:
            - deliveries-net
volumes:
    db-data:
    dev_redis:
networks:
    deliveries-net:
        driver: bridge
