version: "3.8"
services:
    php_delivery:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: delivery_php
        # restart: always
        tty: true
        working_dir: /var/www/html/
        volumes:
            - ./:/var/www/html/
            - ./php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
        networks:
            - delivery-micro-network

    nginx_delivery:
        depends_on:
            - php_delivery
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: appname_nginx
        # restart: always
        tty: true
        ports:
            - "80:80"
        networks:
            - delivery-micro-network

    mysql_delivery:
        image: mariadb:10.1.48
        container_name: mysql_delivery
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
        - 3306:3306
        volumes:
        - ./mysql_delivery:/var/lib/mysql
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
        - delivery-micro-network

volumes:
    mysql_delivery:

networks:
    delivery-micro-network:
        driver: bridge
