name: CI/CD Workflow with Laravel and Docker

on:
  push:
    branches: [ "dev","main" ]
  pull_request:
    branches: [ "dev","main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install PHP Dependencies
      run: sudo apt-get install php-pear librdkafka-dev -y
    - name: Install PHP rdkafka
      run: sudo pecl install rdkafka -y && echo "extension=rdkafka.so" > ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - name: Validate composer.json and composer.lock
      run: composer validate --strict
    - name: Install dependencies
      run: composer update && composer install --prefer-dist --no-progress
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        APP_ENV: testing
        DB_CONNECTION: sqlite
        DB_DATABASE: ":memory:"
      run: php artisan test >> storage/logs/laravel.log
    - name: Check Laravel Log
      run: cat storage/logs/laravel.log
